# Instructions

**Rationale.** The fundamentals of programming (data types, conditional statements, loops, functions) are necessary for you to develop a foundation on which to build data analytics skills. This assignment consists of 2 parts. In the first part, correct the existing code to successfully accomplish the stated task. In the second part, you will be asked to write your own code.

Feel free to add additional cells if/when necessary. Comment your solutions to explain your code to communicate your reasoning. This may help you receive partial credit.

# Part 1 - Fix the code.

Note that there may be multiple mistakes in the code.

1. (3 points) Loop through customer names and select only the ones whose **first name begins with "A"**

In [1]:
customers = [('Adam', 'Smith'),('Mary', 'Samsonite'),('Pancho', 'Sanchez'),('Lily', 'Wang'),('Curtis', 'Jackson'),('Anne', 'Shirley'),('Alex', 'Hamilton'),('Bill', 'Shakespeare'),('Steve', 'Sondeheim')]
# use a list comprehension to select the customer name tuples for which
# the 1st item (first name) begins with 'A'
acustomers = [c for c in customers if c[0][0]=='A']
print(acustomers)

[('Adam', 'Smith'), ('Anne', 'Shirley'), ('Alex', 'Hamilton')]

2. (3 points) Fix the function below that computes the break even price given a product's marginal costs (MC), fixed costs to set up a factory line (FC), and some quantity produced, (Q). Run the function on a series of production quantities given an MC and FC to compute the corresponding break even prices.

Note, break even means the revenue = total costs, i.e. $P\times Q = FC+Q*MC$. One can solve this equation for $P$ to get the break even price, $P = \frac{FC}{Q}+MC$.

In [2]:
def breakevenprice(FC, MC, Q): # fix this line
    P = FC/Q + MC # fix this line
    return P

In [3]:
# Don't change this part
Quantities = [500,1000,1500,2000,2500,3000]
FC = 20000
MC = 20

# fix the errors here:
# make sure the list of break even prices is printed JUST ONCE
BEPrices = []
for Q in Quantities: # loop through Qunatities (error here)
    P = breakevenprice(FC, MC, Q) # compute break even price (error here)
    BEPrices.append(P) # append break even price to the list BEPrices (error here)
    print(BEPrices) # Print out all the break even prices (error here)

[60.0]
[60.0, 40.0]
[60.0, 40.0, 33.333333333333336]
[60.0, 40.0, 33.333333333333336, 30.0]
[60.0, 40.0, 33.333333333333336, 30.0, 28.0]
[60.0, 40.0, 33.333333333333336, 30.0, 28.0, 26.666666666666668]

# Part 2 (4 points) - Write your own code to solve the problem

Suppose you have a list of leads that need to be qualified. Each lead is composed of the following things:

1. ID (integer)
1. Income (Integer)
1. Debt (Integer)
1. Married (1 for married, 0 for not)

Your company has 2 different offers depending on the qualifications of the individual, offer A and offer B.

1. Offer A qualification:
    1. Income is **at least** double their total debt.
    1. Marital status does not matter.
1. Offer B qualifications:
    1. Income is less than twice their total debt
    1. but (income) greater than or equal to half their total debt.
    1. Must be married.
1. Otherwise, no offer is to be made.

Write a function called `offer` that (**2 points**)
1. takes as input: one record of a lead
1. returns "A", "B", or "None" based on the rules above.

**Test this function on a list of leads provided below.** (**2 points**)

Each lead is a tuple of (ID, income, debt, married), i.e. (1, 25000, 12000, 1) is id 1, 25k income, 12k debt, and married.

In [4]:
def offer(record):

  _, income, debt, married = record # Unpack the lead record

  if income >= 2 * debt:

    return "A"

  elif income < 2 * debt and income >= 0.5 * debt and married == 1:

    return "B"

  else:

    return "None"

In [5]:
r = (1, 25000, 12000, 1)
print(offer(r))

A

In [6]:
leads = [
    (1, 25000, 12000, 1),
    (2, 50000, 25000, 0),
    (3, 1250000, 200000, 1),
    (4, 25000, 0, 0),
    (5, 30000, 80000, 1),
    (6, 50000, 80000, 0)
]
for lead in leads:
  result = offer(lead)
  print(f"Lead ID {lead[0]}: Offer {result}")

Lead ID 1: Offer A
Lead ID 2: Offer A
Lead ID 3: Offer A
Lead ID 4: Offer A
Lead ID 5: Offer None
Lead ID 6: Offer None

In [ ]:
from google.colab import drive
drive.mount('/content/drive')